export const colorOptions = [
  {
    value: "slate",
    label: "Slate",
    bg: "bg-slate-100",
    text: "text-slate-500",
  },
  { value: "gray", label: "Gray", bg: "bg-gray-100", text: "text-gray-500" },
  { value: "zinc", label: "Zinc", bg: "bg-zinc-100", text: "text-zinc-500" },
  {
    value: "neutral",
    label: "Neutral",
    bg: "bg-neutral-100",
    text: "text-neutral-500",
  },
  {
    value: "stone",
    label: "Stone",
    bg: "bg-stone-100",
    text: "text-stone-500",
  },
  { value: "red", label: "Red", bg: "bg-red-100", text: "text-red-500" },
  {
    value: "orange",
    label: "Orange",
    bg: "bg-orange-100",
    text: "text-orange-500",
  },
  {
    value: "amber",
    label: "Amber",
    bg: "bg-amber-100",
    text: "text-amber-500",
  },
  {
    value: "yellow",
    label: "Yellow",
    bg: "bg-yellow-100",
    text: "text-yellow-500",
  },
  { value: "lime", label: "Lime", bg: "bg-lime-100", text: "text-lime-500" },
  {
    value: "green",
    label: "Green",
    bg: "bg-green-100",
    text: "text-green-500",
  },
  {
    value: "emerald",
    label: "Emerald",
    bg: "bg-emerald-100",
    text: "text-emerald-500",
  },
  { value: "teal", label: "Teal", bg: "bg-teal-100", text: "text-teal-500" },
  { value: "cyan", label: "Cyan", bg: "bg-cyan-100", text: "text-cyan-500" },
  { value: "sky", label: "Sky", bg: "bg-sky-100", text: "text-sky-500" },
  { value: "blue", label: "Blue", bg: "bg-blue-100", text: "text-blue-500" },
  {
    value: "indigo",
    label: "Indigo",
    bg: "bg-indigo-100",
    text: "text-indigo-500",
  },
  {
    value: "violet",
    label: "Violet",
    bg: "bg-violet-100",
    text: "text-violet-500",
  },
  {
    value: "purple",
    label: "Purple",
    bg: "bg-purple-100",
    text: "text-purple-500",
  },
  {
    value: "fuchsia",
    label: "Fuchsia",
    bg: "bg-fuchsia-100",
    text: "text-fuchsia-500",
  },
  { value: "pink", label: "Pink", bg: "bg-pink-100", text: "text-pink-500" },
  { value: "rose", label: "Rose", bg: "bg-rose-100", text: "text-rose-500" },
];
